language: swift
osx_image: xcode9.4
cache:
  directories:
  - Carthage

install:
- bundle install
- chmod u+x install.sh && ./install.sh
script:
- xcodebuild -scheme InsightClientTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 5S,OS=11.4' test | xcpretty --color
